//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Domain.Models
{
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public System.DateTime Published { get; set; }
        public int Views { get; set; }
        public string ImageUrl { get; set; }
        public string Body { get; set; }
        public int FstClassId { get; set; }
        public int SndClassId { get; set; }
    
        public virtual FstClass FstClass { get; set; }
        public virtual SndClass SndClass { get; set; }
    }
    
}
